spring:
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        cachecontrol:
          max-age: -1
          s-max-age: -1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devoa?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ENC(Wgya2NEwm7fli087vdUyGg==)
    password: ENC(NqU5iqHqaYFABpJ/dNlDrB9OuD1Aique)
    driver-class-name: com.mysql.cj.jdbc.Driver


zjjcnt:
  file-transport:
    type: local
    local:
      root-path: /Users/cyetstar/dev/file